[project]
authors = ["Akhil <akhil.sathuluri@tum.de>"]
channels = ["conda-forge"]
name = "sim_a_splat"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
post_install = "pip install viser==0.2.23"

[dependencies]
python = "3.10.*"
matplotlib = ">=3.10.1,<4"
plotly = ">=6.0.0,<7"
numpy = ">=2.2.3,<3"
urchin = ">=0.0.29,<0.0.30"
pygame = ">=2.6.1,<3"
pymunk = ">=6.10.0,<7"
pip = ">=25.0.1,<26"
meshio = ">=5.3.5,<6"
gymnasium = ">=1.0.0,<2"
ipykernel = ">=6.29.5,<7"
ipympl = ">=0.9.6,<0.10"
ipython = ">=8.33.0,<9"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
torch = "==2.4.1"
torchvision = "==0.19.1"
torchaudio = "==2.4.1"
nerfstudio = ">=1.1.5, <2"
amo-urdf = { git = "git+https://github.com/ami-iit/amo_urdf.git" }
sak = { path = "../sak", editable = true}
drake = ">=1.38.0, <2"
open3d = ">=0.19.0, <0.20"

[system-requirements]
libc = "2.35"
