[project]
authors = ["Akhil <akhil.sathuluri@tum.de>"]
channels = ["conda-forge"]
name = "sim_a_splat"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
plotly = ">=6.1.2,<7"
matplotlib = ">=3.10.3,<4"
urchin = ">=0.0.29,<0.0.30"
pygame = ">=2.6.1,<3"
pymunk = ">=7.0.1,<8"
pip = ">=25.1.1,<26"
meshio = ">=5.3.5,<6"
gymnasium = ">=1.0.0,<2"
ipykernel = ">=6.29.5,<7"
zarr = ">=3.0.8,<4"
libxcrypt = ">=4.4.36,<5"
narwhals = ">=1.43.0,<2"

[pypi-dependencies]
nerfstudio = { git = "git+https://github.com/akhilsathuluri/nerfstudio.git" }
amo-urdf = { git = "git+https://github.com/ami-iit/amo_urdf.git" }
sak = { git = "git+https://github.com/akhilsathuluri/sak.git" }
torch = ">=2.7.1, <3"
torchvision = ">=0.22.1, <0.23"
drake = ">=1.42.0, <2"

[system-requirements]
libc = "2.35"
cuda = "12"
