[workspace]
authors = ["asathuluri <akhil.sathuluri@tum.de>"]
channels = ["conda-forge"]
name = "sim_a_splat"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
plotly = ">=6.1.2,<7"
matplotlib = ">=3.10.3,<4"
urchin = ">=0.0.29,<0.0.30"
pygame = ">=2.6.1,<3"
pymunk = ">=7.0.0,<8"
pip = ">=25.1.1,<26"
meshio = ">=5.3.5,<6"
gymnasium = ">=1.0.0,<2"
ipykernel = ">=6.29.5,<7"
zarr = ">=2.18.3,<3"
libxcrypt = ">=4.4.36,<5"

[pypi-dependencies]
torch = ">=2.7.0, <3"
torchvision = ">=0.22.0, <0.23"
nerfstudio = { git = "git+https://github.com/akhilsathuluri/nerfstudio.git"}
amo-urdf = { git = "git+https://github.com/ami-iit/amo_urdf.git" }
sak = { path = "../sak", editable = true }
drake = ">=1.38.0, <2"

[system-requirements]
libc = "2.35"
cuda = "12"
